dist: xenial
sudo: true
language: scala
scala:
  - 2.13.0
jdk:
  - openjdk8

branches:
  only:
    - deploy1

addons:
  ssh_known_hosts:
    - ${SERVER_IP}: ${SERVER_PORT}

before_install:
  - openssl aes-256-cbc -K $encrypted_92b9c69e620b_key -iv $encrypted_92b9c69e620b_iv
    -in scripts/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install: true

script:
  - sbt clean
  - sbt compile && sbt test
  - sbt universal:packageZipTarball
  - travis_wait 30 scp -C -i ~/.ssh/id_rsa -oStrictHostKeyChecking=no -P ${SERVER_PORT} "`find target/universal -maxdepth 1 -type f -name 'jianmu*.tgz'`" ${USER_NAME}@${SERVER_IP}:${DEPLOY_PATH}
  - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${SERVER_PORT} ${USER_NAME}@${SERVER_IP} 'bash -s' < scripts/deploy.sh ${DEPLOY_PATH} ${SECRET_KEY} ${UPLOAD_TOKEN} "`md5sum \"\`find target/universal -maxdepth 1 -type f -name 'jianmu*.tgz'\`\" | cut -d' ' -f1`"
