dist: xenial
sudo: true
language: scala
scala:
  - 2.13.0
jdk:
  - openjdk8

branches:
  only:
    - deploy1

addons:
  ssh_known_hosts:
    - ${SERVER_IP}: ${SERVER_PORT}

before_install:
  - openssl aes-256-cbc -K $encrypted_92b9c69e620b_key -iv $encrypted_92b9c69e620b_iv
    -in scripts/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install: true

script:
  - sbt clean
  - sbt compile && sbt test
  - sbt universal:packageZipTarball
  - mkdir -p dist
  - find target/universal -type f -name "jianmu*.tgz" -print0 | xargs -t -0 tar -zxv -C dist -f
  - mv "`pwd`/dist/`ls dist`" "`pwd`/dist/jianmu"
  - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${SERVER_PORT} ${USER_NAME}@${SERVER_IP} 'bash -s' < scripts/clean.sh ${DEPLOY_PATH}
  - scp -C -i ~/.ssh/id_rsa -oStrictHostKeyChecking=no -P ${SERVER_PORT} -r dist/jianmu ${USER_NAME}@${SERVER_IP}:${DEPLOY_PATH}
  - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${SERVER_PORT} ${USER_NAME}@${SERVER_IP} 'bash -s' < scripts/deploy.sh ${DEPLOY_PATH} ${SECRET_KEY} ${UPLOAD_TOKEN}
